# Generated by Django 5.2.7 on 2026-06-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(blank=True, max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=255)),
                ('b_form', models.CharField(blank=True, max_length=100)),
                ('dob', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('tribe_caste', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('f_g_name', models.CharField(blank=True, max_length=255)),
                ('f_g_cnic', models.CharField(blank=True, max_length=100)),
                ('f_g_occupation', models.CharField(blank=True, max_length=255)),
                ('f_g_contact', models.CharField(blank=True, max_length=100)),
                ('class_of_admission', models.CharField(blank=True, max_length=100)),
                ('current_class', models.CharField(blank=True, max_length=100)),
                ('date_of_admission', models.CharField(blank=True, max_length=100)),
                ('withdrawn', models.CharField(blank=True, default='no', max_length=100)),
                ('class_of_withdrawl', models.CharField(blank=True, max_length=100)),
                ('current_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('arrear_dues', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
