# Generated by Django 5.2.7 on 2026-06-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.IntegerField(unique=True)),
                ('date_of_admission', models.DateField()),
                ('student_f_name', models.CharField(max_length=100)),
                ('student_l_name', models.CharField(max_length=100)),
                ('b_form', models.CharField(max_length=20, unique=True)),
                ('dob', models.DateField()),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('tribe_caste', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('f_g_name', models.CharField(max_length=100)),
                ('f_g_cnic', models.CharField(max_length=20)),
                ('f_g_occupation', models.CharField(blank=True, max_length=100)),
                ('f_g_contact', models.CharField(max_length=20)),
                ('class_of_admission', models.CharField(max_length=50)),
                ('current_class', models.CharField(max_length=50)),
                ('withdrawn', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('class_of_withdrawal', models.CharField(blank=True, max_length=50)),
                ('arrear_dues', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['admission_no'],
            },
        ),
    ]
