# Generated by Django 5.2.7 on 2026-06-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Individual monthly fee override. Leave blank to use class FeeStructure.', max_digits=10, null=True),
        ),
    ]
