# Generated by Django 5.2.7 on 2026-06-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_class_of_withdrawl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_admission',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='dob',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
