# Generated by Django 5.2.7 on 2026-06-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_add_db_default_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='b_form',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
