# Generated by Django 5.2.7 on 2026-06-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_add_classroom_academicyear_fix_duedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedBalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('data', models.JSONField(help_text='Full balance sheet JSON snapshot')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.AddField(
            model_name='feerecord',
            name='is_advance',
            field=models.BooleanField(default=False, help_text='True if this record was created via advance payment.'),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('waived', 'Waived'), ('advance', 'Paid in Advance')], default='unpaid', max_length=20),
        ),
    ]
